import { zodResolver } from "@hookform/resolvers/zod";
import { Save } from "lucide-react";
import { Controller, useForm } from "react-hook-form";
import { z } from "zod";

import { DateInput } from "@/components/common/date-input";
import { InlineErrorMessage } from "@/components/common/error-state";
import { FormField } from "@/components/common/form-field";
import { SearchableSelect } from "@/components/common/searchable-select";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { ApiError } from "@/features/auth/api";
import { useAuth } from "@/features/auth/hooks";

import { useCreateProjectMutation, useUpdateProjectMutation } from "./hooks";
import type { ProjectMutationPayload, ProjectSummary } from "./types";

const datePattern = /^\d{4}-\d{2}-\d{2}$/;

const projectFormSchema = z.object({
  name: z.string().trim().min(1, "Project name is required.").max(200, "Project name must be 200 characters or fewer."),
  description: z.string().trim().min(1, "Description is required."),
  project_lead_id: z.uuid("Select a project lead."),
  start_date: z.string().regex(datePattern, "Enter a valid start date."),
  end_date: z.string().regex(datePattern, "Enter a valid end date."),
  status: z.enum(["Planning", "Not Started", "Active", "On Hold", "Completed"]),
  funder_partner: z.string().trim().max(255, "Funder/Partner must be 255 characters or fewer.").optional(),
  project_type: z.string().trim().max(100, "Project Type must be 100 characters or fewer.").optional(),
  objectives: z.string().trim().optional(),
  priority: z.enum(["Low", "Medium", "High"]).optional(),
});

type ProjectFormValues = z.infer<typeof projectFormSchema>;

type ProjectFormDialogProps = {
  mode: "create" | "edit";
  project?: ProjectSummary;
  open: boolean;
  onOpenChange: (open: boolean) => void;
  children: React.ReactNode;
};

export function ProjectFormDialog({ children, mode, onOpenChange, open, project }: ProjectFormDialogProps) {
  const { user } = useAuth();
  const createProject = useCreateProjectMutation();
  const updateProject = useUpdateProjectMutation(project?.id ?? "");
  const mutation = mode === "create" ? createProject : updateProject;
  const leadOptions = buildLeadOptions(user, project);
  const {
    control,
    formState: { errors, isSubmitting },
    handleSubmit,
    register,
    reset,
  } = useForm<ProjectFormValues>({
    resolver: zodResolver(projectFormSchema),
    values: projectToFormValues(project, user?.id),
  });
  const serverError = mutation.error ? mutationErrorMessage(mutation.error) : null;
  const isPending = mutation.isPending || isSubmitting;

  function handleOpenChange(nextOpen: boolean) {
    if (!nextOpen) {
      mutation.reset();
      reset(projectToFormValues(project, user?.id));
    }
    onOpenChange(nextOpen);
  }

  async function onSubmit(values: ProjectFormValues) {
    try {
      const saved = await mutation.mutateAsync(toPayload(values));
      reset(projectToFormValues(saved, user?.id));
      onOpenChange(false);
    } catch {
      return;
    }
  }

  return (
    <Dialog open={open} onOpenChange={handleOpenChange}>
      <DialogTrigger asChild>{children}</DialogTrigger>
      <DialogContent className="max-w-3xl">
        <DialogHeader>
          <DialogTitle>{mode === "create" ? "Create Project" : "Edit Project"}</DialogTitle>
          <DialogDescription>
            {mode === "create"
              ? "Create an accessible project record. Project Code is generated by the backend."
              : "Update project fields supported by the backend. Project Code remains read-only."}
          </DialogDescription>
        </DialogHeader>
        <form className="space-y-5" noValidate onSubmit={handleSubmit(onSubmit)}>
          {serverError ? <InlineErrorMessage message={serverError} /> : null}
          {project ? (
            <div className="rounded-md border bg-background px-3 py-2">
              <p className="text-xs font-medium uppercase text-muted-foreground">Project Code</p>
              <p className="mt-1 font-mono text-sm font-semibold text-foreground">{project.code}</p>
            </div>
          ) : null}
          <div className="grid gap-4 md:grid-cols-2">
            <FormField label="Project Name" error={errors.name?.message} required className="md:col-span-2">
              {({ describedBy, id, invalid }) => (
                <Input id={id} aria-describedby={describedBy} aria-invalid={invalid} {...register("name")} />
              )}
            </FormField>
            <FormField label="Description" error={errors.description?.message} required className="md:col-span-2">
              {({ describedBy, id, invalid }) => (
                <Textarea id={id} aria-describedby={describedBy} aria-invalid={invalid} {...register("description")} />
              )}
            </FormField>
            <FormField
              label="Project Lead"
              error={errors.project_lead_id?.message}
              description="User lookup is not available from the backend yet; selectable lead options are limited to users already known to this screen."
              required
            >
              {() => (
                <Controller
                  control={control}
                  name="project_lead_id"
                  render={({ field }) => (
                    <SearchableSelect
                      label="Project Lead"
                      options={leadOptions}
                      value={field.value}
                      onValueChange={field.onChange}
                      placeholder="Select project lead"
                    />
                  )}
                />
              )}
            </FormField>
            <FormField label="Status" error={errors.status?.message} required>
              {() => (
                <Controller
                  control={control}
                  name="status"
                  render={({ field }) => (
                    <Select value={field.value} onValueChange={field.onChange}>
                      <SelectTrigger aria-label="Status">
                        <SelectValue placeholder="Select status" />
                      </SelectTrigger>
                      <SelectContent>
                        {["Planning", "Not Started", "Active", "On Hold", "Completed"].map((status) => (
                          <SelectItem key={status} value={status}>
                            {status}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  )}
                />
              )}
            </FormField>
            <FormField label="Start Date" error={errors.start_date?.message} required>
              {({ describedBy, id, invalid }) => (
                <DateInput id={id} aria-describedby={describedBy} aria-invalid={invalid} {...register("start_date")} />
              )}
            </FormField>
            <FormField label="End Date" error={errors.end_date?.message} required>
              {({ describedBy, id, invalid }) => (
                <DateInput id={id} aria-describedby={describedBy} aria-invalid={invalid} {...register("end_date")} />
              )}
            </FormField>
            <FormField label="Funder/Partner" error={errors.funder_partner?.message}>
              {({ describedBy, id, invalid }) => (
                <Input id={id} aria-describedby={describedBy} aria-invalid={invalid} {...register("funder_partner")} />
              )}
            </FormField>
            <FormField label="Project Type" error={errors.project_type?.message}>
              {({ describedBy, id, invalid }) => (
                <Input id={id} aria-describedby={describedBy} aria-invalid={invalid} {...register("project_type")} />
              )}
            </FormField>
            <FormField label="Priority" error={errors.priority?.message}>
              {() => (
                <Controller
                  control={control}
                  name="priority"
                  render={({ field }) => (
                    <Select value={field.value ?? "none"} onValueChange={(value) => field.onChange(value === "none" ? undefined : value)}>
                      <SelectTrigger aria-label="Priority">
                        <SelectValue placeholder="Select priority" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="none">No priority</SelectItem>
                        {["Low", "Medium", "High"].map((priority) => (
                          <SelectItem key={priority} value={priority}>
                            {priority}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  )}
                />
              )}
            </FormField>
            <FormField label="Objectives" error={errors.objectives?.message} className="md:col-span-2">
              {({ describedBy, id, invalid }) => (
                <Textarea id={id} aria-describedby={describedBy} aria-invalid={invalid} {...register("objectives")} />
              )}
            </FormField>
          </div>
          <DialogFooter>
            <DialogClose asChild>
              <Button type="button" variant="outline" disabled={isPending}>
                Cancel
              </Button>
            </DialogClose>
            <Button type="submit" disabled={isPending || leadOptions.length === 0} className="bg-brand-red text-white hover:bg-brand-red/90">
              <Save className="size-4" aria-hidden="true" />
              {isPending ? "Saving..." : mode === "create" ? "Create Project" : "Save Changes"}
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}

function projectToFormValues(project: ProjectSummary | undefined, currentUserId: string | undefined): ProjectFormValues {
  return {
    name: project?.name ?? "",
    description: project?.description ?? "",
    project_lead_id: project?.project_lead_id ?? currentUserId ?? "",
    start_date: project?.start_date ?? "",
    end_date: project?.end_date ?? "",
    status: project?.status ?? "Planning",
    funder_partner: project?.funder_partner ?? "",
    project_type: project?.project_type ?? "",
    objectives: project?.objectives ?? "",
    priority: project?.priority ?? undefined,
  };
}

function toPayload(values: ProjectFormValues): ProjectMutationPayload {
  return {
    name: values.name.trim(),
    description: values.description.trim(),
    project_lead_id: values.project_lead_id,
    start_date: values.start_date,
    end_date: values.end_date,
    status: values.status,
    funder_partner: blankToNull(values.funder_partner),
    project_type: blankToNull(values.project_type),
    objectives: blankToNull(values.objectives),
    priority: values.priority ?? null,
  };
}

function blankToNull(value: string | undefined) {
  const trimmed = value?.trim();
  return trimmed ? trimmed : null;
}

function buildLeadOptions(user: ReturnType<typeof useAuth>["user"], project: ProjectSummary | undefined) {
  const options = [];

  if (user) {
    options.push({ label: `${user.name} (${user.email})`, value: user.id });
  }

  if (project?.project_lead_id && !options.some((option) => option.value === project.project_lead_id)) {
    options.push({ label: `Current project lead (${project.project_lead_id})`, value: project.project_lead_id });
  }

  return options;
}

function mutationErrorMessage(error: Error) {
  if (error instanceof ApiError) {
    if (error.status === 403) {
      return "You do not have access to update this project.";
    }
    if (error.status === 404) {
      return "The project or selected user could not be found.";
    }
    if (error.status === 409) {
      return "The project could not be saved because it conflicts with existing data.";
    }
    if (error.status === 422 || error.status === 400) {
      return "Please check the project details and try again.";
    }

    return error.message;
  }

  return "The project could not be saved. Please try again.";
}
